version: 1.0.{build}
image: Ubuntu1804
build_script:
- sh: make server
test: off
artifacts:
- path: server
  name: server_x86
deploy:
- provider: GitHub
  tag: server-v$(appveyor_build_version)
  release: server_x86v$(appveyor_build_version)
  auth_token:
    secure: cJ7EnndBscfSyO6ybBnTzm6x/Mk+tbAfFcQLTVeC6TPmQKBjaOx8He14BqVlfkZioqHZzh6qQHT7M42JFQXhRCqx3n7flWCZW0gpTc4Aj7A=
  repository: 4396NeverBeSlaves/simple_http_server
  artifact: server
  draft: false