version: 1.0.{build}
image: Ubuntu1804
build_script:
- sh: make server
test: off
artifacts:
- path: server
  name: server_x86
deploy:
- provider: GitHub
  auth_token:
    secure: OdoOhZ2+EJf0DJWOi243B8YIQZjdGtVNMygkNi0BFE2NZARYToAehIHy6UmHfdvK
  repository: 4396NeverBeSlaves/simple_http_server
  artifact: server
  draft: true
  prerelease: false
  on:
    appveyor_repo_tag: true